> install.packages("igraph")
> library("igraph")
> g <- graph.famous("Krackhardt_Kite")
> vcount(g)
> ecount(g)
> ecount(g)/(vcount(g)*(vcount(g)-1)/2)
> degree(g)
> dg <- graph.formula(1-+2, 1-+3, 2++3)
> plot(dg)
> reciprocity(dg)
> dyad.census(dg)
> kite <- graph.famous("Krackhardt_Kite")
> atri <- adjacent.triangles(kite)
> plot(kite, vertex.label=atri)
> transitivity(kite, type="local")
> adjacent.triangles(kite) / (degree(kite) * (degree(kite)-1)/2)
> library(igraph)
> g2 <- barabasi.game(50, p=2, directed=F)
> g1 <- watts.strogatz.game(1, size=100, nei=5, p=0.05)
> g <- graph.union(g1,g2)
> g <- simplify(g)
> plot(g)